cliente1[0]=A
cliente2[0]=B

r1[0]=AA
r1[1]=EE
r1[2]=CC
r1[exec]=ifconfig eth0 192.168.1.1/24
r1[exec]=ifconfig eth1 10.1.0.1/30
r1[exec]=ifconfig eth1 50.0.0.1/30
r1[exec]=/etc/init.d/isc-dhcp-server start 

clienteb[exec]=dhclient -v 

isp[0]=CC
isp[1]=DD
isp[2]=C
isp[exec]=ifconfig eth0 50.0.0.2/30
isp[exec]=ifconfig eth0 80.0.0.1/30

swa[0]=A
swa[1]=AA
swa[exec]=btcl addbr br0 
swa[exec]=btcl addif br0 eth0 eth1 
swa[exec]=ifconfig br0 up 
swa[exec]=brctl stp br0 on 

vpn[0]=EE
vpn[1]=FF
vpn[exec]=dhclient -v 

web[0]=C
web[exec]=ifconfig eth0 200.10.20.30/30

#LAB DE PESQUISA

r2[0]=DD
r2[1]=FF
r2[2]=BB
r2[exec]=ifconfig eth0 80.0.0.2/30
r2[exec]=ifconfig eth0 192.168.50.1/24
r2[exec]=/etc/init.d/isc-dhcp-server start 

swb[0]=BB
swb[1]=B

cliente2[exec]=dhclient -v 

