pc0[0]=A
pc1[0]=B
pc2[0]=C
pc3[0]=D
sever0[0]=Z

pc0[exec]=ifconfig eth0 192.168.200.1/24
pc1[exec]=ifconfig eth0 192.168.200.2/24
pc2[exec]=ifconfig eth0 192.168.200.3/24
pc3[exec]=ifconfig eth0 192.168.200.4/24
sever0[exec]=ifconfig eth0 192.168.200.100/24

sw0[0]=A
sw0[1]=B
sw0[2]=E
sw0[3]=F

sw0[exec]=brctl addbr br0
sw0[exec]=brctl addif br0 eth0 eth1 eth2 eth3
sw0[exec]=ifconfig br0 up 


sw1[0]=C
sw1[1]=D
sw1[2]=E
sw1[3]=G

sw1[exec]=brctl addbr br1
sw1[exec]=brctl addif br1 eth0 eth1 eth2 eth3
sw1[exec]=ifconfig br1 up 

sw2[0]=E
sw2[1]=F
sw2[2]=G
sw2[3]=Z

sw2[exec]=brctl addbr br2
sw2[exec]=brctl addif br2 eth0 eth1 eth2 eth3
sw2[exec]=ifconfig br2 up 
