pc0[0]=A
pc1[0]=B
dns[0]=C
web[0]=D

dns[exec]=ifconfig eth0 8.8.8.8/28
dns[exec]=route add default gw 8.8.8.1
web[exec]=ifconfig eth0 200.131.5.249/28
web[exec]=route add default gw 200.131.5.248

router0[0]=A
router0[1]=AA
router0[2]=AB
router0[exec]=ifconfig eth0 192.168.10.1/24
router0[exec]=ifconfig eth1 10.0.0.1/30
router0[exec]=ifconfig eth2 50.0.0.1/30
router0[exec]=/etc/init.d/isc-dhcp-server start 
router0[exec]=route add -net 192.168.20.0/24 gw 10.0.0.2
router0[exec]=route add -net 8.8.8.0/28 gw 50.0.0.2
router0[exec]=route add -net 200.131.5.240/28 gw 50.0.0.2

pc0[exec]=dhclient -v 

router1[0]=B
router1[1]=AA
router1[2]=BC
router1[exec]=ifconfig eth0 192.168.20.1/24
router1[exec]=ifconfig eth1 10.0.0.2/30
router1[exec]=ifconfig eth2 30.0.0.1/30
router1[exec]=/etc/init.d/isc-dhcp-server start 
router1[exec]=route add -net 192.168.10.0/24 gw 10.0.0.1
router1[exec]=route add -net 8.8.8.0/28 gw 30.0.0.2 
router1[exec]=route add -net 200.131.5.240/28 gw 30.0.0.2

pc1[exec]=dhclient -v

isp[0]=AB
isp[1]=BC
isp[2]=C
isp[3]=D
isp[exec]=ifconfig eth0 50.0.0.2/30
isp[exec]=ifconfig eth1 30.0.0.2/30
isp[exec]=ifconfig eth2 8.8.8.1/28
isp[exec]=ifconfig eth3 200.131.5.248/28
isp[exec]=route add -net 192.168.20.0/24 gw 30.0.0.1 
isp[exec]=route add -net 192.168.10.0/24 gw 50.0.0.1
