pc1[0]=a
pc2[0]=b
pc3[0]=b 
pc4[0]=a
switch[0]=a
switch[1]=b

pc1[exec]=ifconfig eth0 192.168.100.1/24 
pc2[exec]=ifconfig eth0 192.168.100.2/24 
pc3[exec]=ifconfig eth0 192.168.100.3/24 
pc4[exec]=ifconfig eth0 192.168.100.4/24 

switch[exec]=brctl addbr br0
switch[exec]=brctl addif br0 eth0 eth1
switch[exec]=ifconfig br0 up
