pc0[0]=A
pc1[0]=B

sw0[0]=A
sw0[1]=B
sw0[2]=C
sw0[exec]=brctl addbr br0
sw0[exec]=brctl addif br0 eth0 eth1 eth2
sw0[exec]=ifconfig br0 up
sw0[exec]=brctl stp br0 on

router[0]=C
router[exec]=ifconfig eth0 add 2001:db8:c0ca:c01a::1/64
router[exec]=ifconfig eth0 192.168.1.1/24
router[exec]=/etc/init.d/radvd start
router[exec]=/etc/init.d/isc-dhcp-server start

pc0[sysctl]=net.ipv6.conf.eth0.accept_ra=2
pc1[sysctl]=net.ipv6.conf.eth0.accept_ra=2
pc0[exec]=dhclient -v
pc1[exec]=dhclient -v
