pc0[0]=A
pc1[0]=B
pc2[0]=C
pc3[0]=D
pc4[0]=E
pc5[0]=F

server[0]=CC
server[1]=DD
server[exec]=ifconfig eth0 192.168.100.2/24
server[exec]=ifconfig eth1 192.168.200.2/24
server[exec]=/etc/init.d/isc-dhcp-server start 


sw0[0]=A
sw0[1]=B
sw0[2]=C
sw0[3]=CC
sw0[exec]=brctl addbr br0 
sw0[exec]=brctl addif br0 eth0 eth1 eth2 eth3
sw0[exec]=ifconfig br0 up 
sw0[exec]=brctl stp br0 on 

sw1[0]=D
sw1[1]=E
sw1[2]=F
sw1[3]=DD
sw1[exec]=brctl addbr br1 
sw1[exec]=brctl addif br1 eth0 eth1 eth2 eth3
sw1[exec]=ifconfig br1 up
sw1[exec]=brctl stp br1 on

pc0[exec]=dhclient -v  
pc1[exec]=dhclient -v
pc2[exec]=dhclient -v
pc3[exec]=dhclient -v
pc4[exec]=dhclient -v
pc5[exec]=dhclient -v
