##SUB-REDE 1 
pc0[0]=A
pc1[0]=B
pc2[0]=C
pc3[0]=D
pc4[0]=E
pc5[0]=F
#pc6[0]=G
#pc7[0]=H
#pc8[0]=I
#pc9[0]=J
#pc10[0]=K
#pc11[0]=L
#pc12[0]=M
#pc13[0]=N
#server0[0]=O
#server1[0]=P
#server2[0]=Q

sw0[0]=A
sw0[1]=B
sw0[2]=AA
sw0[3]=BB
sw0[exec]=brtcl addbr br0 
sw0[exec]=brtcl addif br0 eth0 eth1 eth2 eth3 
sw0[exec]=ifconfig br0 up
sw0[exec]=brctl stp br0 on

sw1[0]=C 
sw1[1]=D
sw1[2]=E
sw1[3]=AA
sw1[4]=CC
sw1[exec]=brctl addbr br1 
sw1[exec]=brctl addif br1 eth0 eth1 eth2 eth3 eth4
sw1[exec]=ifconfig br1 up 
sw1[exec]=brctl stp br1 on

sw2[0]=BB
sw2[1]=CC
sw2[2]=F
sw2[3]=DD
sw2[exec]=brctl addbr br2 
sw2[exec]=brctl addif br2 eth0 eth1 eth2 eth3
sw2[exec]=ifconfig br2 up
sw2[exec]=brctl stp br2 on
 
r0[0]=DD
r0[1]=EE
r0[2]=FF
r0[3]=GG
r0[exec]=ifconfig eth0 192.168.100.1/26
r0[exec]=ifconfig eth0 add 2001:db8:p3pi:5ic0::1/64
r0[exec]=ifconfig eth1 10.0.0.1/30
r0[exec]=ifconfig eth2 11.0.0.1/30
r0[exec]=ifconfig eth3 12.0.0.1/30
r0[exec]=/etc/init.d/radvd start 
r0[exec]=/etc/init.d/isc-dhcp-server start 

pc0[exec]=dhclient -v
pc1[exec]=dhclient -v
pc2[exec]=dhclient -v
pc3[exec]=dhclient -v
pc4[exec]=dhclient -v
pc5[exec]=dhclient -v

pc0[sysctl]=net.ipv6.conf.eth0.accept_ra=2
pc1[sysctl]=net.ipv6.conf.eth0.accept_ra=2
pc2[sysctl]=net.ipv6.conf.eth0.accept_ra=2
pc3[sysctl]=net.ipv6.conf.eth0.accept_ra=2
pc4[sysctl]=net.ipv6.conf.eth0.accept_ra=2
pc5[sysctl]=net.ipv6.conf.eth0.accept_ra=2

