pc0[0]=A
pc1[0]=B
pc2[0]=C
server[0]=D

sw0[0]=A
sw0[1]=B
sw0[2]=C
sw0[3]=D

sw0[exec]=brctl addbr br0
sw0[exec]=brctl addif br0 eth0 eth1 eth2 eth3
sw0[exec]=ifconfig br0 up
sw0[exec]=brctl stp br0 on 

server[exec]=ifconfig eth0 192.168.1.2/24
server[exec]=/etc/init.d/isc-dhcp-server start 

pc0[exec]=dhclient -v
pc1[exec]=dhclient -v
pc2[exec]=dhclient -v
