pc0[0]=A
pc1[0]=B
pc2[0]=C
pc3[0]=D 

pc0[exec]=ifconfig eth0 192.168.188.2/24
pc1[exec]=ifconfig eth0 192.168.188.3/24
pc2[exec]=ifconfig eth0 192.168.188.4/24
pc3[exec]=ifconfig eth0 192.168.188.5/24

sw0[0]=A
sw0[1]=B
sw0[2]=E

sw1[0]=C
sw1[1]=D
sw1[2]=E

sw0[exec]=brctl addbr br0
sw0[exec]=brctl addif br0 eth0 eth1 eth2
sw0[exec]=ifconfig br0 up

sw1[exec]=brctl addbr br1
sw1[exec]=brctl addif br1 eth0 eth1 eth2
sw1[exec]=ifconfig br1 up
