pc0[0]=A
pc1[0]=B
pc2[0]=C
pc3[0]=D

sw0[0]=A
sw0[1]=B
sw0[2]=AA
sw0[exec]=brctl addbr br0
sw0[exec]=brctl addif br0 eth0 eth1 eth2
sw0[exec]=ifconfig br0 up
sw0[exec]=brctl stp br0 on 

sw1[0]=C
sw1[1]=D
sw1[2]=BB
sw1[exec]=brctl addbr br1
sw1[exec]=brctl addif br1 eth0 eth1 eth2
sw1[exec]=ifconfig br1 up 
sw1[exec]=brtcl stp br1 on

router[0]=AA
router[1]=BB
router[exec]=ifconfig eth0 add 2001:db8:acad:1ab1::1/64
router[exec]=ifconfig eth1 add 2001:db8:acad:1ab2::1/64
router[exec]=/etc/init.d/radvd start 

pc0[sysctl]=net.ipv6.conf.eth0.accept_ra=2
pc1[sysctl]=net.ipv6.conf.eth0.accept_ra=2
pc2[sysctl]=net.ipv6.conf.eth0.accept_ra=2
pc3[sysctl]=net.ipv6.conf.eth0.accept_ra=2
