pc0[0]=A
pc1[0]=A
pc2[0]=B
pc3[0]=B

router[0]=A
router[1]=B
router[exec]=ifconfig eth0 192.168.100.1/24
router[exec]=ifconfig eth1 192.168.200.1/24
router[exec]=/etc/init.d/isc-dhcp-server start 

pc0[exec]=dhclient -v
pc1[exec]=dhclient -v
pc2[exec]=dhclient -v
pc3[exec]=dhclient -v
