pc0[0]=A 
pc1[0]=B
pc2[0]=C
pc3[0]=D 

pc0[exec]=ifconfig eth0 192.168.10.10/24
pc1[exec]=ifconfig eth0 192.168.10.20/24
pc2[exec]=ifconfig eth0 192.168.10.30/24
pc3[exec]=ifconfig eth0 192.168.10.40/24

sw0[0]=A
sw0[1]=B
sw0[2]=C
sw0[3]=D

sw0[exec]=brctl addbr br0
sw0[exec]=brctl addif br0 eth0 eth1 eth2 eth3
sw0[exec]=ifconfig br0 up 
